# Dockerfile for use with Toolbox

FROM docker.io/endlessm/eos-toolbox:5.1

# Install the dependencies for the build system
RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get install -y \
        java-common \
        ca-certificates-java && \
    apt-get install -y \
        git \
        openjdk-17-jdk-headless \
        python-is-python3 \
        python3 \
        python3-pip \
        python3-venv \
        wget \
        unzip \
        && \
    apt-get clean

# Install Android SDK
ENV ANDROID_HOME=/opt/android/sdk
COPY Makefile /tmp/
RUN make -C /tmp sdk && \
  rm -f /tmp/Makefile

# Put some of the SDK tools in PATH
ENV PATH="${PATH}:${ANDROID_HOME}/cmdline-tools/latest/bin:${ANDROID_HOME}/platform-tools"
